# Generated by Django 3.1.6 on 2021-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=20, verbose_name='Exchange Name')),
            ],
            options={
                'verbose_name_plural': 'StockExchanges',
                'ordering': ['-exchange_name'],
            },
        ),
        migrations.CreateModel(
            name='StockSymbolTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200, verbose_name='Stock Name')),
                ('stock_symbols', models.CharField(max_length=20, verbose_name='Stock Symbols')),
                ('stock_exchange', models.ManyToManyField(related_name='StockExchanges', to='main.StockExchange')),
            ],
            options={
                'verbose_name_plural': 'StockSymbolTables',
                'ordering': ['-stock_name'],
            },
        ),
    ]
