# Generated by Django 3.1.6 on 2021-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=50, verbose_name='TransactionType')),
                ('order_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('alice_blue_order_id', models.CharField(blank=True, max_length=200)),
                ('exchange_symbol', models.CharField(max_length=20, verbose_name='ExChange Symbol')),
                ('input_symbol', models.CharField(max_length=20, verbose_name='Input Symbol')),
                ('exchange_name', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('MCX', 'MCX'), ('FUTURE OPTION', 'FUTURE OPTION')], max_length=15, verbose_name='ExChange')),
                ('instrumentname', models.CharField(max_length=20, verbose_name='InstrumentName')),
                ('ordertype', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL', 'StopLossLimit'), ('SL-M', 'StopLossMarket')], max_length=50, verbose_name='OrderType')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product_type', models.CharField(choices=[('I', 'Intraday'), ('D', 'Delivery'), ('CO', 'CoverOrder'), ('BO', 'BracketOrder')], max_length=50, verbose_name='PoductType')),
                ('max_profit', models.FloatField(verbose_name='Maximum Profit')),
                ('max_loss', models.FloatField(verbose_name='Maximum Loss')),
                ('strategy_tag', models.CharField(choices=[('START1', 'START1'), ('START2', 'START2'), ('START3', 'START3')], max_length=50, verbose_name='StrategyTag')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date of Order')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=20, verbose_name='Exchange Name')),
            ],
            options={
                'verbose_name_plural': 'StockExchanges',
                'ordering': ['-exchange_name'],
            },
        ),
        migrations.CreateModel(
            name='StockSymbolTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Name')),
                ('stock_symbols', models.CharField(max_length=20, verbose_name='Stock Symbols')),
                ('stock_exchange', models.ManyToManyField(related_name='StockExchanges', to='main.StockExchange')),
            ],
            options={
                'verbose_name_plural': 'StockSymbolTables',
                'ordering': ['-stock_name'],
            },
        ),
    ]
