# Generated by Django 3.1.6 on 2021-03-21 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymboltable',
            name='stock_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Name'),
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('exchange_symbol', models.CharField(max_length=20, verbose_name='ExChange Symbol')),
                ('input_symbol', models.CharField(max_length=20, verbose_name='Input Symbol')),
                ('instrumentname', models.CharField(max_length=20, verbose_name='InstrumentName')),
                ('entryordertype', models.CharField(choices=[('Market', 'Market')], max_length=50, verbose_name='EntryOrederType')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product_type', models.CharField(choices=[('MIS', 'MIS')], max_length=50, verbose_name='PoductType')),
                ('max_profit', models.FloatField(verbose_name='Maximum Profit')),
                ('max_loss', models.FloatField(verbose_name='Maximum Loss')),
                ('strategy_tag', models.CharField(choices=[('START1', 'START'), ('START2', 'START2'), ('START3', 'START3')], max_length=50, verbose_name='StrategyTag')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date of Order')),
                ('exchange_name', models.ManyToManyField(to='main.StockExchange')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
