# Generated by Django 3.1.6 on 2021-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210321_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
