# Generated by Django 3.1.6 on 2021-03-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210321_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='date_time',
            field=models.DateTimeField(auto_created=True, verbose_name='Date of Order'),
        ),
    ]
