# Generated by Django 3.1.6 on 2021-03-21 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210321_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='exitordertype',
            field=models.CharField(choices=[('Market', 'Market')], default=django.utils.timezone.now, max_length=50, verbose_name='ExitOrederType'),
            preserve_default=False,
        ),
    ]
